stages:
  data_processing:
    cmd: python src/data/data_processing.py
    deps:
    - src/data/data_processing.py
    - data/raw/appartments.csv
    - data/raw/gurgaon_properties.csv
    outs:
    - data/processed/preprocessed_dataset_1.csv

  feature_engineering:
    cmd: python src/data/feature_engineering.py
    deps:
    - data/processed
    - src/data/feature_engineering.py
    outs:
    - data/featured_data/preprocessed_dataset_v2.csv
  outlier_treatment:
    cmd: python src/outliers/outlier_treatment.py
    deps:
    - data/featured_data
    - src/outliers/outlier_treatment.py
    outs:
    - data/outliers_treated/outlier_treated_data.csv
  missing_values_imputation:
    cmd: python src/missing_values/missing_values_imputation.py
    deps:
    - data/outliers_treated
    - src/missing_values/missing_values_imputation.py
    outs:
    - data/missing_value_imputation/missing_value_imputated_data.csv
  feature_selection:
    cmd: python src/feature_selection/feature_selection.py
    deps:
    - data/missing_value_imputation
    - src/feature_selection/feature_selection.py
    outs:
    - data/feature_selection/post_feature_selection_data.csv

  model_selection:
    cmd: python src/models/model_selection.py
    deps:
    - data/feature_selection
    - src/feature_selection/feature_selection.py
    outs:
    - data/final_x_train/final_x_train.pkl
    - data/final_x_train/final_y_train.pkl
    - model/xg_boost_pipeline.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - data/final_x_train/final_x_train.pkl
    - data/final_x_train/final_y_train.pkl
    - params.yaml
    metrics:
    - model/model_metric.json:
        cache: false
