stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/processed

  feature_engineering:
    cmd: python src/data/feature_engineering.py
    deps:
    - data/processed
    - src/data/feature_engineering.py
    outs:
    - data/featured_data
  outlier_treatment:
    cmd: python src/outliers/outlier_treatment.py
    deps:
    - data/featured_data
    - src/outliers/outlier_treatment.py
    outs:
    - data/outliers_treated
  missing_values_imputation:
    cmd: python src/missing_values/missing_values_imputation.py
    deps:
    - data/outliers_treated
    - src/missing_values/missing_values_imputation.py
    outs:
    - data/missing_value_imputation
  feature_selection:
    cmd: python src/feature_selection/feature_selection.py
    deps:
    - data/missing_value_imputation
    - src/feature_selection/feature_selection.py
    outs:
    - data/feature_selection

  model_selection:
    cmd: python src/models/model_selection.py
    deps:
    - data/feature_selection
    - src/feature_selection/feature_selection.py
    outs:
    - data/final_x_train
    - models
