stages:
  data_ingestion:
    cmd: python real_estate_ml_project/src/data/data_ingestion.py
    deps:
    - real_estate_ml_project/src/data/data_ingestion.py
    outs:
    - real_estate_ml_project/data/processed

  feature_engineering:
    cmd: python real_estate_ml_project/src/data/feature_engineering.py
    deps:
    - real_estate_ml_project/data/processed
    - real_estate_ml_project/src/data/feature_engineering.py
    outs:
    - real_estate_ml_project/data/featured_data
  outlier_treatment:
    cmd: python real_estate_ml_project/src/outliers/outlier_treatment.py
    deps:
    - real_estate_ml_project/data/featured_data
    - real_estate_ml_project/src/outliers/outlier_treatment.py
    outs:
    - real_estate_ml_project/data/outliers_treated
  missing_values_imputation:
    cmd: python real_estate_ml_project/src/missing_values/missing_values_imputation.py
    deps:
    - real_estate_ml_project/data/outliers_treated
    - real_estate_ml_project/src/missing_values/missing_values_imputation.py
    outs:
    - real_estate_ml_project/data/missing_value_imputation
  feature_selection:
    cmd: python real_estate_ml_project/src/feature_selection/feature_selection.py
    deps:
    - real_estate_ml_project/data/missing_value_imputation
    - real_estate_ml_project/src/feature_selection/feature_selection.py
    outs:
    - real_estate_ml_project/data/feature_selection

  model_selection:
    cmd: python real_estate_ml_project/src/models/model_selection.py
    deps:
    - real_estate_ml_project/data/feature_selection
    - real_estate_ml_project/src/feature_selection/feature_selection.py
    outs:
    - real_estate_ml_project/data/final_x_train
    - real_estate_ml_project/models
