name: CI Pipeline

on: push

jobs:
  real_estate_poject_testing:
    runs-on: ubuntu-latest

    steps:
      - name: checout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/checkout@v2
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro

      - name: run model test
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          python -m unittest tests/test_model.py

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -name: Build Docker Image
        if: success()
        run: |
            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/real_estate_app:v1
        
      -name: Push Docker Imgae to Docker Hub
        if: success()
        run: |
            docker push ${{secrets.DOCKER_HUB_USERNAME}}//real_estate_app:v1